# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jokesapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jokesapp
  pod 'RNMobileCenter', '~> 0.4.0'
  pod 'MobileCenter', '~> 0.6.0'

  

  target 'jokesappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'jokesapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jokesapp-tvOS

  target 'jokesapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
